# up from build image

manager:
  image: chaserdocker_manager
  ports:
    - "3000:3000"
  working_dir: /chaserver-master
  command: node ./manager/manager.js

server:
  image: chaserdocker_server
  ports:
    - "40000:40000"
    - "50000:50000"
  links:
    - manager
  working_dir: /chaserver-master
  command: python ./server/server.py
