FROM node

#ENV http_proxy http://157.114.64.104:8080
#ENV https_proxy http://157.114.64.104:8080
#ENV no_proxy 157.114.64.104

RUN apt-get -y update

RUN apt-get -y install unzip

#RUN npm -g config set proxy http://157.114.64.104:8080
#RUN npm -g config set https-proxy http://157.114.64.104:8080


RUN wget https://github.com/lrks/chaserver/archive/master.zip
RUN unzip master.zip

WORKDIR /chaserver-master

RUN npm -y install socket.io

CMD node ./manager/manager.js

EXPOSE 3000 40000 50000

